#!/bin/bash

sed -Ene 's/^([-[:alnum:]]+): *([-:<@>,\._ [:alnum:]]+)$/\1 \2/p' | while read -r a b; do
    echo -n "${a//-/_}" | tr '[:lower:]' '[:upper:]'
    # escape special characters in the value
    echo "=$b" | sed -e 's/\([<> ]\)/\\\1/g'
done
