#!/bin/bash

set -eu

test_get_commit_pragmas() {
    local msg='Use external action

Run-GHA: true
Skip-PR-comments: true
Test-tag: always_passes,vm

Required-githooks: true

Signed-off-by: Brian J. Murrell <brian.murrell@intel.com>
'
    assert_equals "$(echo "$msg" | ../get_commit_pragmas)" 'RUN_GHA=true
SKIP_PR_COMMENTS=true
TEST_TAG=always_passes,vm
REQUIRED_GITHOOKS=true
SIGNED_OFF_BY=Brian\ J.\ Murrell\ \<brian.murrell@intel.com\>'

    local msg='Escape spaces also

'"'"'Will-not-be-a-pragma: false'"'"' should not be considered a commit
pragma, but:
Should-not-be-a-pragma: bar will be because it was not quoted.

Skip-func-test-leap15: false
RPM-test-version: 2.5.100-13.10036.g65926e32
Skip-PR-comments: true
Test-tag: always_passes always_fails
EL8-VM9-label: all_vm9
EL9-VM9-label: all_vm9
Leap15-VM9-label: all_vm9
HW-medium-label: new_icx5
HW-large-label: new_icx9

Required-githooks: true

Signed-off-by: Brian J. Murrell <brian.murrell@intel.com>
'
    assert_equals "$(echo "$msg" | ../get_commit_pragmas)" 'SHOULD_NOT_BE_A_PRAGMA=bar\ will\ be\ because\ it\ was\ not\ quoted.
SKIP_FUNC_TEST_LEAP15=false
RPM_TEST_VERSION=2.5.100-13.10036.g65926e32
SKIP_PR_COMMENTS=true
TEST_TAG=always_passes\ always_fails
EL8_VM9_LABEL=all_vm9
EL9_VM9_LABEL=all_vm9
LEAP15_VM9_LABEL=all_vm9
HW_MEDIUM_LABEL=new_icx5
HW_LARGE_LABEL=new_icx9
REQUIRED_GITHOOKS=true
SIGNED_OFF_BY=Brian\ J.\ Murrell\ \<brian.murrell@intel.com\>'

    local msg='Test PR-repos pragma

PR-repos: argobots@PR-23:91

Required-githooks: true

Signed-off-by: Brian J. Murrell <brian.murrell@intel.com>
Run-GHA: true
Skip-PR-comments: true
'
    assert_equals "$(echo "$msg" | ../get_commit_pragmas)" 'PR_REPOS=argobots@PR-23:91
REQUIRED_GITHOOKS=true
SIGNED_OFF_BY=Brian\ J.\ Murrell\ \<brian.murrell@intel.com\>
RUN_GHA=true
SKIP_PR_COMMENTS=true'

}
