name: bash_unit Tests
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  bash-unit-testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Unit testing with bash_unit
      run: |
        curl -s https://raw.githubusercontent.com/pgrange/bash_unit/master/install.sh | bash
        FORCE_COLOR=true ./bash_unit tests/test_*
